### ISSUE TITLE
strip the namespace prefix from the ingress host?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/exposecontroller#107]
when using helm we need to give each release a unique global name. So on Jenkins X we've been using "$namespace-$appName" as the name.

This leads to duplication in ingress names; they end up as http://jx-staging-myapp.jx-staging.mydomain which is a bit sucky.

It'd be nice to have a flag in exposecontroller we could enable by default that strips the namespace prefix from the host names in the generated ingresses so they appear as the more natural: http://myapp.jx-staging.mydomain

**Comment by romil-punetha** [comment]
Any updates on this? This is stopping me from using the expose controller and I have to use an ingress.yaml instead
