### ISSUE TITLE
Ingress does not update when Service is updated

### ISSUE THREAD

**Issue by hazim1093** [jenkins-x/exposecontroller#116]
# Problem
Ingress is not updated when there is a change in the service. 

# How to Reproduce
Simply add an annotation to an existing service which is to be propagated to the ingress, and it won't work as expected. You will have to delete the ingress manually so that it is recreated by expose controller.

**Comment by hazim1093** [comment]
@jstrachan @rawlingsj 
We'd be happy to contribute and implement this, but I wanted to know first if there's a reason for this behavior or any known hurdles in implementing this?

**Comment by rasheedamir** [comment]
@jstrachan @rawlingsj any thoughts? as we are going to fix this anyways but the question is should we maintain a fork ourselves or raise PR which you guys can merge?

**Comment by rawlingsj** [comment]
Sounds great!  I can't think of any reason why this shouldn't happen.

**Comment by rasheedamir** [comment]
@rawlingsj we will fix it!
