### ISSUE TITLE
User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/exposecontroller#119]
`jx install` returns `Error: Job failed: BackoffLimitExceeded`

```
kubectl logs jobs/expose
F0321 12:47:02.256736       1 exposecontroller.go:175] failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope
```

Giving the `sa/expose` node permissions I could reinstall but just to fail later with 

```
F0321 12:57:26.751324       1 exposecontroller.go:175] failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: no known automatic ways to get an external ip to use with nip.  Please configure exposecontroller configmap manually see https://github.com/jenkins-x/exposecontroller#configuration
```

so I reinstalled again with `jx install --domain mydomain.example.com` and then it succeeded, should have been clearer

**Comment by carlossg** [comment]
Same installation failure on GKE (after several installation attempts)

```
helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.624 --values=/Users/csanchez/.jx/gitSecrets.yaml --values=/Users/csanchez/.jx/adminSecrets.yaml --values=/Users/csanchez/.jx/extraValues.yaml --namespace=jx --timeout=6000
Error: Job failed: BackoffLimitExceeded
make: *** [install] Error 1
Error: Command failed  make ARGS=--values=/Users/csanchez/.jx/gitSecrets.yaml --values=/Users/csanchez/.jx/adminSecrets.yaml --values=/Users/csanchez/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
error: exit status 2
```

then looking at the job logs

```
$ kubectl logs $(kubectl get pods -a -o name | grep expose | head -n 1)
I0411 07:06:21.610264       1 exposecontroller.go:59] Using build: '2.3.56'
I0411 07:06:21.651445       1 config.go:22] No /etc/exposecontroller/config.yml file found.  Will try to figure out defaults
W0411 07:06:21.651497       1 exposecontroller.go:80] %!s(<nil>)
I0411 07:06:21.655415       1 exposecontroller.go:86] Using ConfigMapo exposecontroller to load configuration...
I0411 07:06:21.655514       1 exposecontroller.go:94] Loaded ConfigMap exposecontroller to load configuration!
I0411 07:06:21.655536       1 exposecontroller.go:102] Config file before overrides exposer: Ingress
http: true
tls-acme: false
I0411 07:06:21.655557       1 exposecontroller.go:128] Config file after overrides exposer: Ingress
http: true
tls-acme: false
I0411 07:06:21.655566       1 exposecontroller.go:172] Running in : `jx`
I0411 07:06:21.655723       1 controller.go:73] NewController true
I0411 07:06:21.655775       1 strategy.go:48] stratagy.New true
I0411 07:06:21.655796       1 ingress.go:33] NewIngressStrategy 1 true
F0411 07:06:21.701948       1 exposecontroller.go:175] failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope: Unknown user "system:serviceaccount:jx:expose"
```

**Comment by carlossg** [comment]
The solution was again (both in aws and gke)

    jx install --domain mydomain.example.com

Otherwise the expose controller needs a clusterrole with node permissions for whatever reason

**Comment by rawlingsj** [comment]
Rather than giving exposecontroller a cluster role we could probably sort this in jx install by looking for an existing ingress controller to work out a default nip.io and prompt for the users domain.

**Comment by allen-servedio** [comment]
Hit the same issue against the IBM Cloud:

```
F0703 18:51:08.812850       1 exposecontroller.go:175] failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope
```

As with Carlos, I was able to get around the issue by adding `--domain <Ingress subdomain from Bluemix console>`. So:

```
jx install --provider ibm --domain my-cluster-name-here.us-south.containers.mybluemix.net
```

**Comment by vochicong** [comment]
@deyceg How did you handle the problem? Could you reinstall exposecontroller configmap manually?

**Comment by vochicong** [comment]
I was able to reinstall `exposecontroller` configmap by running `jx install` again.

**Comment by vishnoisuresh** [comment]
Hi, I am having similar issues. Is it possible to recreate **exposecontroller configmap**  during the `jx upgrade platform` ?

**Comment by almerico** [comment]
got the same issue today

**Comment by gbrivate** [comment]
I'm having a similar issue but with a exposecontroller-service and I do need to reinstall it without break everything else.. =D

**Comment by antonputra** [comment]
Having the same issue on gke, `failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx-staging:expose" cannot list nodes at the cluster scope`

**Comment by vfarcic** [comment]
I'm experiencing the same issue since I installed the latest `jx`. The same steps (running in GKE) worked with one of the previous releases.

**Comment by khell** [comment]
Having the same issue on a brand new fresh install of jx on AKS.

**Comment by rverma-nikiai** [comment]
Getting the same issue when passing ingress-class

**Comment by AndreasKnapp1812** [comment]
If using `jx boot`, here is the fix for the second error: https://kubernetes.slack.com/archives/C9MBGQJRH/p1571782518259500?thread_ts=1571777399.254100&cid=C9MBGQJRH

**Comment by aweis89** [comment]
Still having this issue

**Comment by aweis89** [comment]
> If using `jx boot`, here is the fix for the second error: https://kubernetes.slack.com/archives/C9MBGQJRH/p1571782518259500?thread_ts=1571777399.254100&cid=C9MBGQJRH

Anyone able to post the above solution for `jx boot` for those of us that don't have a slack kubernetes authorization?
