### ISSUE TITLE
wrong proxy_pass?

### ISSUE THREAD

**Issue by andre82hh** [jenkins-x/exposecontroller#17]
Hi,

hopefuly this is the right repo for my issue.

I have a kubernetes cluster 1.3.6 running on CoreOS stable 1122.2

and a wildcard dns lab2.dev.xxx.de pointing the k8s-master. The k8s master runs with status _Ready,SchedulingDisabled_ and 1 minion with Status _Ready_

according the [docu](http://fabric8.io/guide/getStarted/kubernetes.html) i try to install fabric8 with this command

```
gofabric8 deploy -d lab2.dev.xxx.de -y
```

After installer i got this output

Opening URL http://fabric8.default.lab2.dev.xxx.de

But i can no reach this url.

when i try to debug this:

```
$ kubectl --namespace fabric8-system exec ingress-nginx-3146896821-9grze cat /etc/nginx/conf.d/default-fabric8.conf

upstream default-fabric8-fabric8.default.lab2.dev.xxx.de-fabric8 {

    server 10.2.79.49:9090;
}


server {
    listen 80;



    server_name fabric8.default.lab2.xxx.de;

    location / {
        proxy_http_version 1.1;

        proxy_connect_timeout 10s;
        proxy_read_timeout 10s;
        client_max_body_size 2000m;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://default-fabric8-fabric8.default.lab2.dev.xxx.de-fabric8;
    }
}
```

Clould it be that there is a wrong generated proxy_pass String? http://default-fabric8-fabric8.default.lab2.dev.xxx.de-fabric8
imho the proxy_pass should be the internal DNS `http://fabric8.default` in the cluster i am able to reach that dns from ingress container.

greetings
Andre

**Comment by rawlingsj** [comment]
I think the problem is your wildcard dns is pointing to your kubernetes-master, it needs to point to the public IP of the node that's running the nginx-ingress controller.

The console output when running `gofabric8 deploy` should have output the node name that the ingress controller was deployed on.  Another way to find out is to run
```
kubectl get nodes -l fabric8.io/externalIP=true
```
This is the label that's added to the node to ensure the NGINX controller is always deployed on it.
