### ISSUE TITLE
fabric8.io annotation not being added to ingress

### ISSUE THREAD

**Issue by romil-punetha** [jenkins-x/exposecontroller#175]
Ive added the line `fabric8.io/ingress.annotations: "nginx.ingress.kubernetes.io/force-ssl-redirect: true"` in the annotations section for a service. However, this annotation is added to the service annotations rather than ingress annotations. Is this behaviour expected? If yes, is there any way to write annotations for ingress through values.yaml?
The other option I have is that I turn off expose controller and I write my own ingress file.

**Comment by rawlingsj** [comment]
The annotations are copied from the service to the ingress when exposecontroller creates it, we do the same here https://github.com/jenkins-x/jenkins-x-platform/blob/6a69d48d8c766755d861926a5359bea9976a2f14/values.yaml#L655

I wonder if it's worth checking the ingress again to see if the annotations are there too?

**Comment by romil-punetha** [comment]
` "annotations": {
      "fabric8.io/generated-by": "exposecontroller",
      "kubernetes.io/ingress.class": "nginx"
    }`
This is the annotation section of the ingress. I don't see the annotations here. 
`
service:
  name: doorman
  type: ClusterIP
  externalPort: 5008
  internalPort: 5008
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
    fabric8.io/ingress.annotations: "nginx.ingress.kubernetes.io/force-ssl-redirect: true"
`
This is what the values in the values.yaml looks like. Any idea where I may be making the mistake? I tried rebuilding the application, however did not observe the expected behaviour.

**Comment by rawlingsj** [comment]
Can you try the approach in the linked example above?  My guess is one os overwritting the other.  i.e.

```
fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/force-ssl-redirect: true"
```

**Comment by romil-punetha** [comment]
Yeah, even I thought that could be an issue. Just tried your suggestion @rawlingsj . No luck. I already had the service created and just updated the application. It also says that the service age is 3 hours, while my pod age is 5 mins, which means that the service never got updated. Could this be an issue? In case it is, let's suppose I delete and recreate the app and it works as expected, shouldn't updating the chart also trigger an update in service and subsequently the ingress?

**Comment by romil-punetha** [comment]
@rawlingsj I deleted the application and recreated it and it worked. Could we have an update where simply publishing a new version of the app is able to make the required changes?
