### ISSUE TITLE
Istio virtualservice / gateway exposestrategy

### ISSUE THREAD

**Issue by jsharpe** [jenkins-x/exposecontroller#187]
If a cluster is using istio ingress gateways it would be good to be able to get exposecontroller to manage the generation of virtualservices and gateways as an alternative exposestrategy

**Comment by sstubbs** [comment]
This would be a great feature.

**Comment by jalonsoa** [comment]
Hello,
  I'm trying to develop this new expose strategy (expose as istio virtualservice), but I have problems to install the dependencies for istio modules. This package use glide as dependency manager, but when I use glide to get dependencies I have this error:

```
$ glide get k8s.io/apimachinery/pkg/apis/meta/v1#^v0.18.2
...
[ERROR]	Failed to set version on k8s.io/kubernetes to 52492b4bff99ef3b8ca617d385a3ff0612f9402d: Unable to update checked out version: exit status 128
[ERROR]	Failed to set initial config references: Unable to update checked out version: exit status 128

```
I'm searching for this commit on git://github.com/openshift/kubernetes.git repo (as indicated by the glide.yaml file), but this commit don't exists on this repo.

any ideas to resolve dependencies ?

thanks
j

**Comment by jalonsoa** [comment]
Hello,
  I have a functional first version with this exposestrategy. To make it work I have updated the kubernetes libraries of the project. I have done it in a different pullrequest. When that pullrequest is approved, I'll upload this with the new exposestrategy

#203
