### ISSUE TITLE
Selenium hub outdated commands

### ISSUE THREAD

**Issue by angoothachap** [jenkins-x/exposecontroller#190]
(https://github.com/jenkins-x/exposecontroller/tree/master/vendor/k8s.io/kubernetes/examples/selenium#using-google-container-engine)
The command needs to be changed in the documentation to:
`kubectl expose rc selenium-hub --name=selenium-hub-external --labels="app=selenium-hub,external=true" --type=LoadBalancer`

Also, (https://github.com/jenkins-x/exposecontroller/tree/master/vendor/k8s.io/kubernetes/examples/selenium#deploy-firefox-and-chrome-nodes)
Change commands to: `kubectl create --filename=selenium-node-chrome-rc.yaml` and `kubectl create --filename=selenium-node-firefox-rc.yaml` respectively

**Comment by jstrachan** [comment]
note that those examples are from the main k8s source code; they are brought in by the vendoring of exposecontroller. I'm not totally sure where the docs have moved to though as this is an ancient fork of k8s by the openshift project: https://github.com/openshift/kubernetes/tree/52492b4bff99ef3b8ca617d385a3ff0612f9402d/examples/selenium

I think these docs have moved somewhere else.

If anything we could maybe add better docs on using selenium on the jenkins x website maybe?
