### ISSUE TITLE
minishift - external IP mapping

### ISSUE THREAD

**Issue by kameshsampath** [jenkins-x/exposecontroller#2]
when fabric8 deployed with minishift, there is an issue with the components getting the right external ip assigned.

`oc export node;oc export service fabric8;oc export service jenkins`

https://gist.github.com/kameshsampath/0e5c7ef8321821581109aa7d4eeae0bd
# expose controller logs

https://gist.github.com/kameshsampath/e7c746e4a479d02b1818b8b124b46dd7

**Comment by rawlingsj** [comment]
I've not seen this error before `Failed to add the fabric8.io/exposeUrl to service nexus Service "nexus" is invalid: spec.externalIPs: Forbidden: externalIPs have been disabled`

I wonder if there was an issue during gofabric8 deploy when it was adding roles.  Could you try running:
```
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:default:exposecontroller
```

and see if that makes any difference.  If that doesn't work could you let us know a bit more about your setup, is this minishift / oc cluster up / CDK / dedicated?

**Comment by jimmidyson** [comment]
From https://access.redhat.com/solutions/2464791:

> OpenShift 3.2 by default will rejected services created with external IPs. The new networkConfig.externalIPNetworkCIDRs parameter has been added to the master-config.yaml file to control the allowable values for external IPs. By default, it is empty, which rejects all values. Cluster administrators can set it to 0.0.0.0/0 to emulate the behavior from OpenShift Enterprise 3.1.

Why do we need to set `externalIP` anyway?

**Comment by rawlingsj** [comment]
oh sorry - I'd totally missed that!  All I saw in the error above was `fabric8.io/exposeUrl` which when looking quickly I missed `externalIPs `.  We shouldnt be setting it, unless its during an update and its applying the same value?

**Comment by davsclaus** [comment]
btw it worked for me before updating minishift from 0.5.0 to 0.6.0. Today I trashed it all and created with new minishift 0.6.0 release which has a new OS3 release also.

**Comment by kameshsampath** [comment]
actually things get started/deployed well - but if you see the service urls over the fabric console you will see the discrepancies metioned above
