### ISSUE TITLE
Configmap Annotaitons - Not updated

### ISSUE THREAD

**Issue by kameshsampath** [jenkins-x/exposecontroller#30]
when we deploy an configmap along with a service and use the annotations `expose.config.fabric8.io/url-key` - and if there is a delay in the expose of the service the value of the key is set to `IP:0` and its observed that the map never gets updated even the service is available after some time

Environment:

`gofabric8, version 0.4.112 (branch: 'master', revision: '50d5d75')
  build date:       '20161202-12:52:33'
  go version:       '1.7.3'
`
`minikube version: v0.13.1`

Reproduce:

You can use the following projects to reproduce the issue:

https://github.com/kameshsampath/keycloak-demo-server - this is will deploy the keycloak server and creates a configmap `keycloak-demo-server`, post deployment if you do `kubectl get configmap keycloak-demo-server -o yaml` you will see the following output "keycloak-demo-server--host-ip" and as `IP:0` 

Because of this the ENV Variable used in this application https://github.com/kameshsampath/springboot-keycloak-demo is pointing to wrong value.

I observed that after a long time the values of the configmap `keycloak-demo-server` get set to right value.

should we synchronize it correctly? and make the dependent application come up with right values ? 

Or Is there something we need to do at application level ?

**Comment by jstrachan** [comment]
exposecontroller should be updating the `fabric8.io/exposeUrl` annotation whenever the Service is updated in any way really.  I wonder if the issue is that the `fabric8.io/exposeUrl` never gets updated correctly in the first place?
