### ISSUE TITLE
Not exposing services via Ingress in Kubernetes cluster

### ISSUE THREAD

**Issue by jamelseagraves** [jenkins-x/exposecontroller#40]
I am trying to deploy fabric8 to a Kubernetes cluster running on EC2 instances. Based on the documentation, exposecontroller should default to using Ingress for exposing services in Kubernetes. For some reason, it keeps using NodePort, so the exposecontroller container fails to run because I have multiple nodes in the cluster. The error log from the stopped container is: `[exposecontroller.go:66] failed to create new strategy: failed to create node port expose strategy: node port strategy can only be used with single node clusters - found 2 nodes`

I even tried explicitly setting the `--ingress=true` flag in the `gofabric8 deploy` command, but the issue is the same. Not sure what is going on. Any thoughts on the root cause of this would be greatly appreciated.

**Comment by Secathor** [comment]
Did you set the `domain` parameter in gofabric8 deploy command ?

> domain when using either Kubernetes Ingress or OpenShift Routes you will need to set the domain that you've used with your DNS provider (fabric8 uses cloudflare) or nip.io if you want a quick way to get running.
