### ISSUE TITLE
allow exposecontroller to be used as a CLI tool and an init-container inside pods

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/exposecontroller#44]
e.g. it'd be nice to add exposecontroller as an init container inside the gogs pod:
https://github.com/fabric8io/fabric8-devops/tree/master/gogs

so that it invokes something like:
```
$> exposecontroller --service gogs
exposecontroller updated ConfigMap of gogs...
```
so that we can use gogs as a stand alone app and folks don't have to run exposecontroller separately

**Comment by jstrachan** [comment]
I wonder if an init-container can update a ConfigMap before a pod starts (and for it to load the updated ConfigMap) mind you - but whether or not that works, it'd be nice to be able to invoke exposecontroller from a CLI - for example as a one shot operation as part of a CI / CD pipeline.

e.g. rather than watching resources in a namespace, folks could just run exposecontroller after a CI / CD pipeline has done a deploy; to then annotate Deployments / Services or update ConfigMaps etc

**Comment by jstrachan** [comment]
so maybe the default operation for `exposecontroller` when running it as a pod is something like...
```
exposecontroller run
```
then if you want a one shot processing you can do something like:
```
exposecontroller service foo
```
to run the expose logic in the named service. 
Or to use a label selector:

```
exposecontroller service -l cheese=foo
```

**Comment by jstrachan** [comment]
actually another option folks might wanna do is a periodic job to run exposecontroller

**Comment by jstrachan** [comment]
maybe the service/run CLI arguments are not required - we just have an optional `-w` or `--watch` flag like `kubectl get pod` that indicates to watch - versus just list and process then return immediately?

So the usual use of exposecontroller becomes....
```
exposecontroller -w
```
then inside a CI / CD flow we'd do something like...
```
exposecontroller -n myuser-stage
```
to process the services / configmaps in the `myuser-stage` namespace?

**Comment by chmouel** [comment]
It's probably just semantic but I would think that by default a tool like this would run as `oneshot` and if we add a --daemon (or -w if you prefer) then it would run as daemon mode while watching the change. either way I'll start working on this
