### ISSUE TITLE
Kube-lego with GKE load balancer

### ISSUE THREAD

**Issue by soarten** [jenkins-x/exposecontroller#76]
When using the native GKE load balancer in combination with kube-lego. The expose controller generated ingress should contain an extra annotation:

`kubernetes.io/ingress.class: gce`

When kube-lego detects this annotation it enhances the given ingress with an extra path mapping leading to the the lego-nginx backend enabling the domain check. 

Adding the annotation by hand triggers kube-lego as well. But after some time the expose controller overwrites the lego path rule with it's own base rule; effectively disabling TLS again.

Is there an option to have the expose controller apply the extra ingress class annotation and prevent it from overwriting the lego acme path extension?

**Comment by rawlingsj** [comment]
We can add the extra annotation, here's an example https://github.com/fabric8io/exposecontroller/blob/master/exposestrategy/ingress.go#L84-L87 although I'm not totally sure of the issue because I have a GKE cluster with ingress rules + certs generated by kube-lego working right now.  What impact are you expecting the extra annotation to have?  

FWIW this PR might interest you too as it means you can add custom annotations to the exposecontroller configmap that will be used when creating ingress rules https://github.com/fabric8io/exposecontroller/pull/75

**Comment by soarten** [comment]
You are referring to the `kubernetes.io/tls-acme` annotation which is working fine indeed. It is the premier incentive having kube-lego doing its thing. 

However without the second kubernetes.io/ingress.class = gce annotation kube-lego will create a second ingress descriptor in its own namespace. When using an nginx ingress-controller the two separate ingresses for a single domain result in a joined loadbalancer rule somehow ordering both ingresses. 

When using the native GKE loadbalancer this won't work. As far as I understand each ingress corresponds to a single loadbalancer. By adding the `kubernetes.io/ingress.class = gce` annotation kube-lego injects its acme path mapping into the first ingress; the one previously created by the exposecontroller. 

Being able to add custom annotations is very nice. In this case it probably won't prevent the exposecontroller from overwriting the lego adaptations of its's ingress rule. It appears that after some time the exposecontroller overwrites the kube-lego adaption of its rules undoing the lego path mapping and disabling tls again.

**Comment by rawlingsj** [comment]
@soarten in a few mins the CI job should build and push a snapshot image we can both test.  If you keep an eye on this PR https://github.com/fabric8io/exposecontroller/pull/77 you should see a comment appear shortly.  If all seems ok can you let me know and I'll merge and release.

**Comment by soarten** [comment]
Isn't this solution a bit to coarse? It could break installations using an nginx ingress controller which is the kube-lego default where the ingress class previously was absent. The outcome of this might be equivalent to the old approach using a two ingresses, but I'm not sure about that.

Besides this it won't prevent the exposecontroller from overwriting the path mapping injected by kube lego. Or am I missing something?
