### ISSUE TITLE
wonder if we should default to a namespaced label instead of 'expose'. Maybe fabric8.io/expose?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/exposecontroller#8]
not 100% sure the correct format of labels, but assume its like annotations?

**Comment by jimmidyson** [comment]
Yes you can use same format as annotations now.

**Comment by rhuss** [comment]
+1 since its an infrastructure label not specific to service itself. 

just out of curiosity, why can't this be an annotation ? from my feeling this seems to be more appropriate since it triggers some 'behaviour'.

**Comment by jstrachan** [comment]
you can't easily watch or filter services via annotations - only labels

**Comment by rawlingsj** [comment]
it's also easier to add a label which then exposes it externally

```
oc label svc foo expose=true
```

**Comment by jimmidyson** [comment]
You can do `oc annotate svc foo expose=true` too btw (& with `kubectl`). It does make more sense to be an annotation in my mind. We can easily filter in expose controller if we did switch to annotations.
