### ISSUE TITLE
Ignores watchNamespaces config

### ISSUE THREAD

**Issue by rasheedamir** [jenkins-x/exposecontroller#84]
The exposecontroller only watches the current namespace; and it ignores the "watchNamespaces" config value

**Comment by rasheedamir** [comment]
As discussed with @rawlingsj that now the recommended approach is to run one exposecontroller per namespace; so, that we can have better control.

Though this is still a bug which should be fixed.

**Comment by r4j4h** [comment]
Agreed. The help text implies `watch-current-namespace: false` should re-engage watching all namespaces but it seems to behave the same either way.

**Comment by gintautassulskus** [comment]
So at the moment there is no way to have a single `exporsecontroller` for all namespaces?

**Comment by gintautassulskus** [comment]
Ok, so it seems that command line parameters or their default values always overwrite config file parameters.
The workaround at the moment is to use command line parameters. E.g. the following config would instruct the controller to watch all namespaces and use Ingress.
```
        args:
          - --watch-current-namespace=false
          - --exposer=Ingress
```
