### ISSUE TITLE
routes that use port 443 should use https protocol

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/exposecontroller#9]
The route of the manageiq microservice is http://manageiq.openshift-infra.vagrant.f8, but the images use 443. So the route should be defined to https, not http.

**Comment by rawlingsj** [comment]
From memory the manageiq route needs passthrough too so that should be checked how we do that also.

**Comment by jimmidyson** [comment]
Each strategy should be configurable via annotations.
